---
abstract: 'methods to inspect the dirtiness of a git repository'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Git-Repository-Plugin-Dirty
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: '0'
  Cwd: '0'
  File::Temp: '0'
  Git::Repository: '0'
  Git::Repository::Plugin: '0'
  Path::Tiny: '0'
  Test::Exception: '0'
  Test::More: '0'
  Test::Trap: '0'
version: '0.01'
